config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
  
  #Route for Edit and Update
  post 'concerts/:id/edit', to: 'concerts#edit', as: :edit_concert
  patch 'concerts/:id', to: 'concerts#update'

  get '/auth/:provider/callback' => 'sessions#omniauth'
  #get '/auth/spotify/callback', to: 'users#spotify'
  
  resources :concerts do
    resources :experiences
  end
  #resources :experiences
  resources :artists
  
  resources :users do
    resources :concerts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/concert.rb
class Concert < ApplicationRecord
    belongs_to :artist
    belongs_to :user
  
    has_many :experiences, dependent: :delete_all #deletes all associated experiences with the concert
    has_many :users, through: :experiences
  
    accepts_nested_attributes_for :artist

    validates :venue, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :date, presence: true, uniqueness: { scope: :date, message: "already taken" }
    #scope above date validation to user
    #scope :order_by_date, -> {Concert.joins(:experiences).group(:id).order('(date) desc')}
   
    def self.concert_date
      order(date: :desc)
    end
  
    #validate :not_a_duplicate

    def artist_attributes=(attributes)
      self.artist = Artist.find_or_create_by(attributes) if !attributes['name'].empty?
      self.artist
    end

    #def not_a_duplicate
     # concert = Concert.find_by(date: date, artist_id: artist_id)
      #if !!date && date != self
       # errors.add(:artist, 'Concert has been added for this date')
      #end
    #end

    #def artist_name
     # artist.try(:name)
    #end

    #def date_and_artist
     # "#{date} - #{artist.try(:name)}"
    #end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
    before_action :set_concert, only:[:show, :edit, :update]
    #before_action :authenticate_user!, :except => [:index]
    before_action :redirect_if_not_logged_in

    def index
        @concerts = Concert.concert_date
       # if params[:user_id]
       #     @concert = User.find(params[:user_id]).concerts
        #    flash.now[:danger] = "You haven't added any concerts yet!" if @concerts.empty?
        #end
    end

    def new
        @concerts = Concert.new
        @concerts.build_artist
        #@concerts.review.build
    end

    def create
       # byebug
        @concerts = Concert.new(concert_params)
        @concerts.user_id = session[:user_id]
        if @concerts.save
            redirect_to concerts_path(@concerts)
        else
            render :new 
        end
    end

    def show
        @concerts = Concert.find(params[:id])
    end

    def edit
        @concert = Concert.find(params[:id])
    end

    def update
        @concert = Concert.find(params[:id])
        @concert.update(params.require(:concert).permit(:venue, :city, :state, :date, :artist_id, artist_attributes: [:name, :genre]))
        redirect_to concerts_path(@concerts)
    end

    def destroy
        @concert = Concert.find(params[:id])
        @concert.destroy
        flash[:danger] = "Concert was successfully deleted"
        redirect_to concerts_path(@concerts)
    end


    private

    def concert_params
        params.require(:concert).permit(:venue, :city, :state, :date, :artist_id, artist_attributes: [:name, :genre])
    end

    def date
    end

    def set_concert
        @concert = Concert.find_by(params[:id])
        redirect_to concerts_path if !@concert
    end

end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/edit.html.erb
<%= form_for @concert do |f|%>

    <p> Select an Existing Artist </p>
        <%#= f.label :artist_id, "Select a Artist" %>
        <%= f.collection_select :artist_id, Artist.all, :id, :name, include_blank: 'Select One'%>

    <p> Add a New Artist </p>
        <%= f.fields_for :artist do |a| %>
            <%= a.label :name %>
            <%= a.text_field :name %>

            <%= a.label :genre %>
            <%= a.text_field :genre %>
        <% end %>

    <br>
    <p>Concert Information </p>


    <%= f.label :venue %>
    <%= f.text_field :venue %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.date_field :date, class: 'form-control' %>

    <br>
    <br>
    
    
    <%= f.submit %>

<% end %>

app/views/concerts/index.html.erb
<h1>Concerts Attended</h1>
 
<table>
 
  <tbody>
    <% @concerts.map do |c|%>
      <tr>
        <td><%= c.artist.name %></td>
        <td><%= link_to "Artist Info", artist_path(c.id)%>
        <td><%= c.venue %></td>
        <td><%= c.city %></td>
        <td><%= c.state %></td>
        <td><%= c.date %></td>
        <td><%= link_to "New Experience", new_concert_experience_path(c.id)%>
        <td><%#= link_to "Your Experience", experience_path(c.id) %>
        <td><%#= link_to "Your Experience", concert_experience_path(c.id, @experiences) %>
        <td><%= link_to "Experiences", concert_experiences_path(c.id) %>

        <% if c.user.id == current_user.id %>
          <td><%= button_to "Edit concert", edit_concert_path(c.id), method: :edit %>
          <td><%= button_to "Delete concert", concert_path(c.id), method: :delete, data: { confirm: "Are you sure you want to delete the concert?"}, class: "btn btn-xs btn-danger" %>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>
<br>
 
<%= link_to "New concert", new_concert_path %>

app/views/concerts/new.html.erb
<%= render partial: 'layouts/errors', locals:{object: @concerts} %>

<h1>New Concert</h1>

<%= form_for(@concerts) do |f|%>

    <p> Select an Existing Artist </p>
        <%#= f.label :artist_id, "Select a Artist" %>
        <%= f.collection_select :artist_id, Artist.all, :id, :name, include_blank: 'Select One'%>

    <p> Add a New Artist </p>
        <%= f.fields_for :artist do |a| %>
            <%= a.label :name %>
            <%= a.text_field :name %>

            <%= a.label :genre %>
            <%= a.text_field :genre %>
        <% end %>

    <br>
    <p>Concert Information </p>

   

    <%= f.label :venue %>
    <%= f.text_field :venue %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.date_field :date, class: 'form-control' %>

    <br>
    <br>
    
    
    <%= f.submit %>

<% end %>