config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  delete '/logout' => 'sessions#destroy'
  
  #Route for Edit and Update
  post 'concerts/:id/edit', to: 'concerts#edit', as: :edit_concert
  patch 'concerts/:id', to: 'concerts#update'

  get '/auth/:provider/callback' => 'sessions#omniauth'
  #get '/auth/spotify/callback', to: 'users#spotify'
  
  resources :concerts do
    resources :experiences
  end
  #resources :experiences
  resources :artists
  
  resources :users do
    resources :concerts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyConcertExperience</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
      <% if logged_in?%>
        <%= link_to "Add a Concert", new_concert_path %> |
        <%= link_to "All Concerts", concerts_path %> |
        <%= link_to "Logout", logout_path, method:"delete"%>

      <% else %>
        <%=link_to "Sign Up", signup_path %> |
        <%=link_to "Log In", login_path %>
      <% end %>

    </div>

  <body>
    <%= yield %>
  </body>
</html>